/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import headfirst.myimplementation.ch1.MiniDuckSimulator;

public class App {
    public static void main(String[] args) {
        System.out.println(args.length);
        if (args.length == 0) {
            System.out.println("Please choose chapter by params like: ch1");
            return;
        }
        String one = args[0];
        if ("ch1" != one) {
            MiniDuckSimulator.main(args);
        }
    }
}
